// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Muhammadnurbasari",
            "email": "m.nurbasari@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/bdj/data/combine": {
            "get": {
                "security": [
                    {
                        "JWTToken": []
                    }
                ],
                "description": "get all data Combine RS DATA \u0026 Kelurahan DATA",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Combine RS DATA \u0026 Kelurahan DATA"
                ],
                "summary": "get data Combine RS DATA \u0026 Kelurahan DATA",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/combineModel.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "combineModel.Kecamatan": {
            "type": "object",
            "properties": {
                "kode": {
                    "type": "string"
                },
                "nama": {
                    "type": "string"
                }
            }
        },
        "combineModel.Kelurahan": {
            "type": "object",
            "properties": {
                "kode": {
                    "type": "string"
                },
                "nama": {
                    "type": "string"
                }
            }
        },
        "combineModel.Kota": {
            "type": "object",
            "properties": {
                "kode": {
                    "type": "string"
                },
                "nama": {
                    "type": "string"
                }
            }
        },
        "combineModel.Location": {
            "type": "object",
            "properties": {
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                }
            }
        },
        "combineModel.Response": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer",
                    "example": 5
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/combineModel.ResultData"
                    }
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "combineModel.ResultData": {
            "type": "object",
            "properties": {
                "alamat": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "faximile": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "jenis_rsu": {
                    "type": "string"
                },
                "kecamatan": {
                    "$ref": "#/definitions/combineModel.Kecamatan"
                },
                "kelurahan": {
                    "$ref": "#/definitions/combineModel.Kelurahan"
                },
                "kode_pos": {
                    "type": "integer"
                },
                "kota": {
                    "$ref": "#/definitions/combineModel.Kota"
                },
                "location": {
                    "$ref": "#/definitions/combineModel.Location"
                },
                "nama_rsu": {
                    "type": "string"
                },
                "telepon": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "website": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        },
        "BasicAuth": {
            "type": "basic"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "0.1.5",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "SERVICE BDJ",
	Description: "Service bdj",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
